name: skydecor-prod

services:

  # ── Backend ──────────────────────────────────────────────────────────────────
  backend:
    container_name: skydecor-backend-prod
    image: ${DOCKERHUB_USERNAME}/skydecor-backend:latest
    build:
      context: ./backend
      target: production
    restart: always
    env_file:
      - ./backend/.env.production
    environment:
      NODE_ENV: production
    ports:
      - "8000:8000"


  # ── Frontend ─────────────────────────────────────────────────────────────────
  frontend:
    container_name: skydecor-frontend-prod
    image: ${DOCKERHUB_USERNAME}/skydecor-frontend:latest
    build:
      context: ./frontend
      target: production
    restart: always
    env_file:
      - ./frontend/.env
    ports:
      - "80:8080"
