name: skydecor-prod

services:

  # ── Backend ──────────────────────────────────────────────────────────────────
  backend:
    container_name: skydecor-backend-prod
    image: ${DOCKERHUB_USERNAME:?DOCKERHUB_USERNAME is not set}/skydecor-backend:latest
    build:
      context: ./backend
      target: production
    restart: always
    env_file:
      - ./backend/.env.production
    environment:
      NODE_ENV: production
    ports:
      - "8000:8000"


  # ── Frontend ─────────────────────────────────────────────────────────────────
  frontend:
    container_name: skydecor-frontend-prod
    image: ${DOCKERHUB_USERNAME:?DOCKERHUB_USERNAME is not set}/skydecor-frontend:latest
    build:
      context: ./frontend
      target: production
    restart: always
    depends_on:
      - backend
    ports:
      - "80:8080"
