name: Build & Deploy Skydecor Admin Dashboard

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

      - name: "Setup Node.js"
        uses: actions/setup-node@v6
        with:
          node-version: "24"
